[package]
name = "portfolio_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
futures = "0.3.24"
tokio = { version = "1.21.1", features = ["full"] }
yahoo_finance_api = "1.3.0"
